security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_profiler|_wdt|assets|build)/
            security: false
        main:
            lazy: true
            provider: app_user_provider
            entry_point: App\Security\ApiAwareAuthenticationEntryPoint
            form_login:
                login_path: app_login
                check_path: app_login
                default_target_path: app_home
                enable_csrf: true
            user_checker: App\Security\UserChecker
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 2592000
                path: /
                always_remember_me: false
            logout:
                path: app_logout
                target: app_home

    access_control:
    - { path: ^/api/analytics, roles: ROLE_FOURNISSEUR }
    - { path: ^/users, roles: ROLE_ADMIN }
    - { path: ^/products, roles: [ROLE_ADMIN, ROLE_FOURNISSEUR] }
    - { path: ^/product-variations, roles: [ROLE_ADMIN, ROLE_FOURNISSEUR] }
    - { path: ^/commandes, roles: [ROLE_ADMIN, ROLE_FOURNISSEUR] }
    - { path: ^/support, roles: [ROLE_ADMIN, ROLE_FOURNISSEUR] }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
