# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router
app_home:
    path: /
    controller: App\Controller\HomeController::index
    methods: [GET]

app_login:
    path: /login
    controller: App\Controller\LoginController::login
    methods: [GET, POST]

app_logout:
    path: /logout
    controller: App\Controller\LoginController::logout

#users:
user_add:
    path: /users/add
    controller: App\Controller\UserController::add
    methods: [GET, POST]

user_check_email:
    path: /users/check-email
    controller: App\Controller\UserController::checkEmail
    methods: [POST]

user_edit:
    path: /users/edit/{id}
    controller: App\Controller\UserController::edit
    methods: [GET, POST]

user_list:
    path: /users
    controller: App\Controller\UserController::list
    methods: [GET]

user_delete:
    path: /users/delete/{id}
    controller: App\Controller\UserController::delete
    methods: [POST]

#Products:
product_list:
    path: /products
    controller: App\Controller\ProductController::list
    methods: [GET]

product_add:
    path: /products/add
    controller: App\Controller\ProductController::add
    methods: [GET, POST]

product_edit:
    path: /products/edit/{id}
    controller: App\Controller\ProductController::edit
    methods: [GET, POST]

product_delete:
    path: /products/delete/{id}
    controller: App\Controller\ProductController::delete
    methods: [POST]

# Product variations
product_variation_list:
    path: /products/{productId}/variations
    controller: App\Controller\ProductVariationController::list
    methods: [GET]

product_variation_add:
    path: /products/{productId}/variations/add
    controller: App\Controller\ProductVariationController::add
    methods: [POST]

product_variation_edit:
    path: /product-variations/{id}/edit
    controller: App\Controller\ProductVariationController::edit
    methods: [POST]

product_variation_delete:
    path: /product-variations/{id}/delete
    controller: App\Controller\ProductVariationController::delete
    methods: [POST]

