# yaml-language-server: $schema=../vendor/symfony/routing/Loader/schema/routing.schema.json

# This file is the entry point to configure the routes of your app.
# Methods with the #[Route] attribute are automatically imported.
# See also https://symfony.com/doc/current/routing.html

# To list all registered routes, run the following command:
#   bin/console debug:router

#users:
user:
    resource: '../src/Controller/'
    type: attribute

user_add:
    path: /users/add
    controller: App\Controller\UserController::add
    methods: [GET, POST]

user_check_email:
    path: /users/check-email
    controller: App\Controller\UserController::checkEmail
    methods: [POST]

user_edit:
    path: /users/edit/{id}
    controller: App\Controller\UserController::edit
    methods: [GET, POST]

user_list:
    path: /users
    controller: App\Controller\UserController::list
    methods: [GET]

user_delete:
    path: /users/delete/{id}
    controller: App\Controller\UserController::delete
    methods: [POST]